"""Add failed login attempts and lock_until

Revision ID: e7f8bd339e08
Revises: f52e655cb915
Create Date: 2025-12-14 19:32:53.414418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f8bd339e08'
down_revision = 'f52e655cb915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lock_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('lock_until')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
